name = "IO - Arma3Addons"
author = "IO0288"
# mainprefix = "io"
prefix = "ioaa3_def"
# git_hash = 0 # Default: 8
[files]
include = [
    "mod.cpp",      # These files are copied to the build directory by default
    "meta.cpp",     # They do not need to be added to your list
    "LICENSE",
    "logo.paa",
    "keys/*",
    "README.md"
]
exclude = [
    "*.psd"         # By default this list is empty
    # "addons/main/README.md"
]
[properties]
author = "IO0288"
# url = "https://github.com/IO0288"
url = "https://git.io0288.com/IO0288"