loadout_lizi_yiliao = 	[[["BWA3_G38","","ACE_acc_pointer_green","rhsusf_acc_ACOG_RMR",["BWA3_30Rnd_556x45_G36_Tracer",30],[],""],[],[],["BWA3_Uniform2_sleeves_Fleck",[["ACE_MapTools",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_EntrenchingTool",1],["GPNV18_Black",1],["ACE_CableTie",2],["BWA3_DM25",4,1],["BWA3_DM32_Blue",1,1]]],["BWA3_Vest_JPC_Radioman_Fleck",[["greenmag_ammo_556x45_basic_60Rnd",2],["greenmag_item_speedloader",1],["kat_accuvac",1],["kat_X_AED",1],["kat_aatKit",2],["kat_EACA",6],["ACE_tourniquet",4],["ACE_splint",3],["BWA3_30Rnd_556x45_G36_Tracer",6,30],["kat_Carbonate",1,10],["kat_Painkiller",1,10]]],["BWA3_FieldPack_Fleck",[["ACE_epinephrine",5],["ACE_elasticBandage",20],["ACE_personalAidKit",3],["ACE_morphine",5],["ACE_surgicalKit",1],["kat_BVM",1],["kat_IV_16",8],["kat_IO_FAST",8],["kat_bloodIV_O_N_500",5],["kat_bloodIV_O_N",5],["kat_vacuum",1],["kat_chestSeal",5],["kat_larynx",8],["kat_TXA",6],["kat_Penthrox",2,10],["kat_oxygenTank_300",1,200]]],"BWA3_OpsCore_FastMT_SOF_Fleck","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["ace_arsenal_insignia","gf1"],["ace_earplugs",true]]];
loadout_lizi_at = 		[[["BWA3_G38","","ACE_acc_pointer_green","rhsusf_acc_ACOG_RMR",["BWA3_30Rnd_556x45_G36_Tracer",30],[],""],["launch_MRAWS_green_rail_F","","","",["MRAWS_HEAT_F",1],[],""],[],["BWA3_Uniform2_sleeves_Fleck",[["ACE_MapTools",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_CableTie",2],["greenmag_item_speedloader",1],["GPNV18_Black",1],["ACE_morphine",3],["ACE_epinephrine",3],["BWA3_DM25",4,1],["BWA3_DM32_Blue",1,1]]],["BWA3_Vest_JPC_Radioman_Fleck",[["greenmag_ammo_556x45_basic_60Rnd",2],["BWA3_30Rnd_556x45_G36_Tracer",6,30],["BWA3_DM51A1",2,1]]],["BWA3_AssaultPack_Fleck",[["ACE_splint",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["ACE_tourniquet",4],["kat_bloodIV_O_N_500",1],["kat_bloodIV_O_N",1],["kat_PainkillerItem",1],["MRAWS_HEAT_F",1,1]]],"BWA3_OpsCore_FastMT_SOF_Fleck","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["ace_arsenal_insignia","Spetsnaz223rdDetachment"],["ace_earplugs",true]]];
loadout_lizi_base = 	[[["BWA3_G38","","ACE_acc_pointer_green","rhsusf_acc_ACOG_RMR",["BWA3_30Rnd_556x45_G36_Tracer",30],[],""],[],[],["BWA3_Uniform2_sleeves_Fleck",[["ACE_MapTools",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_EntrenchingTool",1],["greenmag_item_speedloader",1],["GPNV18_Black",1],["ACE_morphine",3],["ACE_epinephrine",3],["ACE_CableTie",2],["BWA3_DM25",3,1]]],["BWA3_Vest_JPC_Radioman_Fleck",[["greenmag_ammo_556x45_basic_60Rnd",4],["BWA3_DM51A1",4,1],["BWA3_DM32_Blue",2,1],["BWA3_DM32_Red",1,1],["BWA3_30Rnd_556x45_G36_Tracer",8,30]]],["BWA3_FieldPack_Fleck",[["ACE_elasticBandage",15],["ACE_packingBandage",15],["ACE_tourniquet",4],["kat_bloodIV_O_N",1],["kat_bloodIV_O_N_500",1],["ACE_splint",4],["kat_Painkiller",1,10]]],"BWA3_OpsCore_FastMT_SOF_Fleck","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["ace_arsenal_insignia","Spetsnaz223rdDetachment"],["ace_earplugs",true]]];
loadout_lizi_jianb = 	[[["BWA3_G38","","ACE_acc_pointer_green","rhsusf_acc_ACOG_RMR",["BWA3_30Rnd_556x45_G36_Tracer",30],[],""],[],[],["BWA3_Uniform2_sleeves_Fleck",[["ACE_MapTools",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["greenmag_item_speedloader",1],["GPNV18_Black",1],["ACE_epinephrine",3],["ACE_morphine",3],["BWA3_DM32_Blue",2,1]]],["BWA3_Vest_JPC_Radioman_Fleck",[["greenmag_ammo_556x45_basic_60Rnd",2],["BWA3_DM25",6,1],["BWA3_DM51A1",4,1],["BWA3_30Rnd_556x45_G36_Tracer",8,30]]],["BWA3_Kitbag_Fleck",[["ACE_splint",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["ACE_tourniquet",4],["MineDetector",1],["ACE_DefusalKit",1],["ACE_wirecutter",1],["ace_marker_flags_red",10],["kat_bloodIV_O_N",1],["kat_bloodIV_O_N_500",1],["kat_PainkillerItem",1],["rhs_charge_sb3kg_mag",1,1],["rhs_charge_tnt_x2_mag",2,1]]],"BWA3_OpsCore_FastMT_SOF_Fleck","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["ace_arsenal_insignia","Spetsnaz223rdDetachment"],["ace_earplugs",true]]];
loadout_lizi_zhihui = 	[[["BWA3_G38_AG40","","ACE_acc_pointer_green","rhsusf_acc_ACOG_RMR",["BWA3_30Rnd_556x45_G36_Tracer",30],["1Rnd_HE_Grenade_shell",1],""],[],[],["BWA3_Uniform2_sleeves_Fleck",[["ACE_MapTools",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["greenmag_item_speedloader",1],["GPNV18_Black",1],["ACE_morphine",3],["ACE_epinephrine",3],["BWA3_DM25",3,1]]],["BWA3_Vest_JPC_Radioman_Fleck",[["greenmag_ammo_556x45_basic_60Rnd",2],["BWA3_30Rnd_556x45_G36_Tracer",8,30],["BWA3_DM32_Blue",2,1],["BWA3_DM32_Red",2,1],["BWA3_DM51A1",2,1]]],["tfw_ilbe_blade_coy",[["ACE_splint",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["ACE_tourniquet",4],["kat_bloodIV_O_N",1],["kat_bloodIV_O_N_500",1],["kat_PainkillerItem",1],["1Rnd_Smoke_Grenade_shell",4,1],["1Rnd_SmokeRed_Grenade_shell",2,1],["1Rnd_SmokeBlue_Grenade_shell",2,1],["rhs_mag_M433_HEDP",8,1],["ACE_40mm_Flare_ir",4,1],["UGL_FlareWhite_F",4,1]]],"BWA3_OpsCore_FastMT_SOF_Fleck","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["ace_arsenal_insignia","Spetsnaz223rdDetachment"],["ace_earplugs",true]]];
loadout_lizi_jiqiang = 	[[["BWA3_MG4","","rhs_acc_perst3_g","rhsusf_acc_ACOG_RMR",["rhsusf_100Rnd_556x45_mixed_soft_pouch",100],[],""],[],[],["BWA3_Uniform2_sleeves_Fleck",[["ACE_MapTools",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_CableTie",2],["greenmag_item_speedloader",1],["GPNV18_Black",1],["ACE_epinephrine",3],["ACE_morphine",3],["BWA3_DM25",4,1],["BWA3_DM32_Blue",1,1]]],["BWA3_Vest_JPC_Radioman_Fleck",[["ACE_EntrenchingTool",1],["rhsusf_100Rnd_556x45_soft_pouch",4,100],["BWA3_DM51A1",2,1]]],["BWA3_AssaultPack_Fleck",[["ACE_splint",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["ACE_tourniquet",4],["greenmag_beltlinked_556x45_basic_100",5],["kat_bloodIV_O_N_500",1],["kat_bloodIV_O_N",1],["ACE_personalAidKit",1],["kat_PainkillerItem",1]]],"BWA3_OpsCore_FastMT_SOF_Fleck","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["ace_arsenal_insignia","Spetsnaz223rdDetachment"],["ace_earplugs",true]]];
loadout_lizi_liudang = 	[[["BWA3_G38_AG40","","ACE_acc_pointer_green","rhsusf_acc_ACOG_RMR",["BWA3_30Rnd_556x45_G36_Tracer",30],["rhs_mag_M441_HE",1],""],[],[],["BWA3_Uniform2_sleeves_Fleck",[["ACE_MapTools",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_EntrenchingTool",1],["greenmag_item_speedloader",1],["GPNV18_Black",1],["ACE_morphine",3],["ACE_epinephrine",3],["ACE_CableTie",2],["BWA3_DM25",3,1]]],["BWA3_Vest_JPC_Radioman_Fleck",[["greenmag_ammo_556x45_basic_60Rnd",2],["BWA3_DM51A1",2,1],["BWA3_30Rnd_556x45_G36_Tracer",8,30],["BWA3_DM32_Blue",2,1],["1Rnd_Smoke_Grenade_shell",5,1],["1Rnd_SmokeRed_Grenade_shell",2,1],["1Rnd_SmokeBlue_Grenade_shell",2,1]]],["BWA3_FieldPack_Fleck",[["ACE_splint",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["ACE_tourniquet",4],["kat_bloodIV_O_N_500",1],["kat_bloodIV_O_N",1],["ACE_personalAidKit",1],["kat_PainkillerItem",1],["rhs_mag_M433_HEDP",10,1],["rhs_mag_M397_HET",10,1]]],"BWA3_OpsCore_FastMT_SOF_Fleck","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["ace_arsenal_insignia","Spetsnaz223rdDetachment"],["ace_earplugs",true]]];
loadout_lizi_jings_1 = 	[[["BWA3_G28","","ACE_acc_pointer_green","SPS_Optic_SnB_US_3_20_RMR_RAL8000",["ace_20rnd_762x51_mk319_mod_0_mag",20],[],"BWA3_bipod_Harris"],[],["sps_hk_vp9_stnd_ral8000_black","","","SPS_Trijicon_RMR_Black",["16Rnd_9x21_Mag",17],[],""],["BWA3_Uniform2_sleeves_Fleck",[["ACE_MapTools",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_CableTie",2],["greenmag_item_speedloader",1],["ACE_RangeCard",1],["SPS_PVS24LR",1],["ACE_morphine",3],["ACE_epinephrine",3],["GPNV18_Black",1],["ACE_Kestrel4500",1]]],["BWA3_Vest_JPC_Rifleman_Fleck",[["greenmag_ammo_762x51_basic_60Rnd",2],["muzzle_snds_One_Sand_H",1],["BWA3_DM25",6,1],["BWA3_DM51A1",2,1],["ace_20rnd_762x51_mk319_mod_0_mag",6,20]]],["BWA3_AssaultPack_Fleck_Medic",[["ACE_splint",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["ACE_tourniquet",4],["ACE_Tripod",1],["ACE_EntrenchingTool",1],["kat_bloodIV_O_N_500",1],["kat_bloodIV_O_N",1],["16Rnd_9x21_Mag",4,17],["kat_Painkiller",1,10]]],"BWA3_OpsCore_FastMT_SOF_Fleck","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["ace_arsenal_insignia","Spetsnaz223rdDetachment"],["ace_earplugs",true]]];
loadout_lizi_jings_2 =	[[["BWA3_G29","","","SPS_Optic_SnB_US_3_20_RMR_RAL8000",["BWA3_10Rnd_86x70_G29",10],[],"BWA3_bipod_Harris"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["BWA3_Uniform2_sleeves_Fleck",[["ACE_MapTools",1],["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_CableTie",2],["greenmag_item_speedloader",1],["ACE_RangeCard",1],["SPS_PVS24LR",1],["ACE_morphine",3],["ACE_epinephrine",3],["GPNV18_Black",1],["ACE_Kestrel4500",1]]],["BWA3_Vest_JPC_Radioman_Fleck",[["greenmag_ammo_338_basic_60Rnd",2],["BWA3_DM25",6,1],["BWA3_DM51A1",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["BWA3_10Rnd_86x70_G29",5,10]]],["BWA3_AssaultPack_Fleck",[["ACE_splint",4],["ACE_elasticBandage",15],["ACE_packingBandage",15],["ACE_tourniquet",4],["ACE_Tripod",1],["muzzle_snds_SPS_AI_PB_H",1]]],"BWA3_OpsCore_FastMT_SOF_Fleck","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["ace_arsenal_insignia","Spetsnaz223rdDetachment"],["ace_earplugs",true]]];

["ODST新兵装-医疗", loadout_lizi_yiliao#0] call ace_arsenal_fnc_addDefaultLoadout;
["ODST新兵装-反坦克", loadout_lizi_at#0] call ace_arsenal_fnc_addDefaultLoadout;
["ODST新兵装-基础", loadout_lizi_base#0] call ace_arsenal_fnc_addDefaultLoadout;
["ODST新兵装-尖兵", loadout_lizi_jianb#0] call ace_arsenal_fnc_addDefaultLoadout;
["ODST新兵装-指挥", loadout_lizi_zhihui#0] call ace_arsenal_fnc_addDefaultLoadout;
["ODST新兵装-机枪", loadout_lizi_jiqiang#0] call ace_arsenal_fnc_addDefaultLoadout;
["ODST新兵装-榴弹", loadout_lizi_liudang#0] call ace_arsenal_fnc_addDefaultLoadout;
["ODST新兵装-精确射手G28", loadout_lizi_jings_1#0] call ace_arsenal_fnc_addDefaultLoadout;
// ["ODST新兵装-精确射手G29", loadout_lizi_jings_2#0] call ace_arsenal_fnc_addDefaultLoadout;

_items = flatten ([loadout_lizi_yiliao, loadout_lizi_at, loadout_lizi_base, loadout_lizi_jianb, loadout_lizi_zhihui, loadout_lizi_jiqiang, loadout_lizi_liudang, loadout_lizi_jings_1, loadout_lizi_jings_2]);
_items = _items arrayIntersect _items select {
	_x isEqualType "" && { _x != "" }
};
[player, _items] call ace_arsenal_fnc_addVirtualItems;

true;
