class SPS_hk416_11_glm_black_f {
  model = "SPS_hk416_11_glm";
  addonsgroup = "black_f";
  barrelgroup = "black_f";
  boltgroup = "black_f";
  frame = "black_f";
  receiver = "black_f";
  ris = "black_f";
  spuhrmount = "black_f";
  stock = "black_f";
  swingplate = "black_f";
  t1body = "black_f";
};
class SPS_hk416_11_glm_ral8000_f {
  model = "SPS_hk416_11_glm";
  addonsgroup = "f";
  barrelgroup = "f";
  boltgroup = "f";
  frame = "ral8000_f";
  receiver = "ral8000_f";
  ris = "ral8000_f";
  spuhrmount = "ral8000_f";
  stock = "f";
  swingplate = "ral8000_f";
  t1body = "ral8000_f";
};
class SPS_hk416_11_glm_fde_f {
  model = "SPS_hk416_11_glm";
  addonsgroup = "f";
  barrelgroup = "f";
  boltgroup = "f";
  frame = "fde_f";
  receiver = "fde_f";
  ris = "fde_f";
  spuhrmount = "fde_f";
  stock = "f";
  swingplate = "fde_f";
  t1body = "fde_f";
};
