name: HEMTT Build
run-name: HEMTT Build
on:
  workflow_dispatch:
  push:
    branches:
    - release
jobs:
  hemtt-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Release with HEMTT
      uses: gruppe-adler/action-release-with-hemtt@3.0.0
      with:
        # Zip the build
        zip_build: true
        # Working directory
        cwd: .